### ISSUE TITLE
Broken Gravity Last Updated date

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [daleosm/pihole-panel#1]
![image](https://user-images.githubusercontent.com/13170204/54084069-5f6b4b80-432c-11e9-8991-8ea5fa808eea.png)
Surely a wrong syntax somewhere. I´m on Ubuntu Studio 18.10.
Other than that, overall, this is pretty sweet and convenient app, Thanks !

**Comment by daleosm** [comment]
Thanks for letting me know. I've noticed my docker container maintainer has given up updating the image and no one else has mentioned it on Reddit. I will issue an update shortly.

**Comment by daleosm** [comment]
Resolved
