### ISSUE TITLE
Unable to install on Raspbian on RPi 3

### ISSUE THREAD

**Issue by cktechie2012** [daleosm/pihole-panel#4]
Unable to install on Raspbian on RPi 3

me2015ydnruapi@Pi28723641:~$ sudo dpkg --force-all -i PiHole-Panel-latest.deb
dpkg-deb: error: 'PiHole-Panel-latest.deb' is not a debian format archive
dpkg: error processing archive PiHole-Panel-latest.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 PiHole-Panel-latest.deb

Raspbian version: 
Linux  4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux

**Comment by daleosm** [comment]
I've solved this issue, I never anticipated people to run it locally on their Pi. I'm sure this is about to quickly change with the Pi4. XD Thanks
